name: Create Release

on:
  push:
    tags:
      - 'v*'
      
jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup foreman
        uses: rojo-rbx/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build asset
        run: rojo build src/default.project.json --output notify.rbxm
        
      - name: Git Release
        uses: anton-yurchenko/git-release@v4.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG_FILE: "docs/changelog.md"
        with:
          args: |
            ./notify.rbxm
