name: Publish To Roblox

on:
  push:
    branches: 
    - main

jobs:
  ci:
    name: CI and Deployment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: Roblox/setup-foreman@v1
      with:
        version: "^1.0.0"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Report tool versions
      run: rojo --version

    - name: Deploy
      run: |
        rojo upload --cookie "$ROBLOSECURITY" --asset_id 9516265838 src
      env:
        ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
